### ISSUE TITLE
npm install doesn't work on Windows

### ISSUE THREAD

**Issue by BenjaminNitschke** [dashevo/DashJS#11]
### Expected Behavior
Would be nice if this works on windows too, imo many more potential developers.

### Current Behavior
npm install dash crashes with:
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Miner4\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17763
[...]
npm ERR! errno 1
npm ERR! grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! Failed at the grpc@1.24.2 install script.

### Steps to Reproduce & logs
just run npm install dash from Visual Studio Code on any Windows OS

**Comment by Alex-Werner** [comment]
Good evening @BenjaminNitschke ! Thank you for filing this bug !
Support of DashJS with Windows OS is obviously a requirement. 
Can you provide me a `node --version` ?
I will look at it tomorrow on my Windows machine.

**Comment by BenjaminNitschke** [comment]
Seems I still had v10, just updated to the latest version and it installs now (same as on Ubuntu and MacOS).
PS D:\code\dashevo> npm --version
6.13.4
PS D:\code\dashevo> node --version
v12.14.0

Connecting works, but I get the same annoying warnings of dashcore-lib I get on other platforms:
PS D:\code\dashevo> node .\testdashevo.js
More than one instance of dashcore-lib found. Please make sure that you are not mixing instances of classes of the different versions of dashcore.
More than one instance of dashcore-lib found. Please make sure that you are not mixing instances of classes of the different versions of dashcore.
More than one instance of dashcore-lib found. Please make sure that you are not mixing instances of classes of the different versions of dashcore.
connected

**Comment by PastaPastaPasta** [comment]
These 'warnings' are known and are a remnant from bitcoinJS, these warnings should be resolved in a future version. It doesn't affect actually using the library
