### ISSUE TITLE
(getaddrinfo ENOTFOUND seed-2.evonet.networks.dash.org 

### ISSUE THREAD

**Issue by zhangxiaocong** [dashevo/DashJS#114]
my code is
const Dash = require("dash");
const mnemonic = 'pass sponsor rubber august card aim dawn fuel post puppy olive manage'// your mnemonic here.
const client = new Dash.Client({
  network: "testnet",
  wallet: {
    mnemonic: "arena light cheap control apple buffalo indicate rare motor valid accident isolate",
  }
});
client.wallet.getAccount().then(async (account) => {
  // const transaction = account.createTransaction({
  //   recipient:"yNPbcFfabtNmmxKdGwhHomdYfVs6gikbPf",
  //   satoshis:10000
  // });
  // const transactionId = await account.broadcastTransaction(transaction);
});

(node:81153) Error: Failed to perform standard injections with reason: Plugin ChainPlugin of type Standard onStart failed. Reason: getaddrinfo ENOTFOUND seed-2.evonet.networks.dash.org
    at /Users/houzi/WebstormProjects/DashJSmaster/node_modules/dash/node_modules/@dashevo/wallet-lib/src/types/Account/_initializeAccount.js:45:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:81153) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

i cant find where to set seed node, and why this happend

@antouhou

**Comment by antouhou** [comment]
We're currently updating the network infrastructure for 0.14 release, the seed it currently down. It should go live again in a couple of hours

**Comment by zhangxiaocong** [comment]
if i want to set the seed myself to a fixed seed,  where i should set this seed In code.

**Comment by antouhou** [comment]
There's no seed at the moment, we're updating the network at the moment. It will be up soon, I'll post an update in this issue. Thank you!

**Comment by antouhou** [comment]
The update is finished, the network is up and running. Everything should work out of the box. Thank you!

**Comment by antouhou** [comment]
Since there was no response in 10 days, I'm closing the issue.

**Comment by imanmousaei** [comment]
I have the same problem. This is my code : 
```
const Dash = require("dash");

const client = new Dash.Client({
    network: "evonet",
    wallet: {
        mnemonic: null,
    },
});

const account = await client.getWalletAccount();
```

and I get this error :  
```
(node:14728) UnhandledPromiseRejectionWarning: PluginInjectionError: Failed to perform standard injections with reason: Plugin ChainPlugin of type Standard onStart failed: getaddrinfo ENO
TFOUND seed-3.evonet.networks.dash.org
    at C:\Users\Aysa Tech\WebstormProjects\arz2arz-backend\node_modules\@dashevo\wallet-lib\src\types\Account\_initializeAccount.js:57:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a p
romise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.
html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:14728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a no
n-zero exit code.
```



I also tried to ping these and I also got an error ( 'dash.org' works but 'seed.evonet.networks.dash.org' doesnt ) : 

![dash_network_not_resolved](https://user-images.githubusercontent.com/33493057/110208841-ac904280-7e9e-11eb-9396-6b8b78cbda01.PNG)


@antouhou

**Comment by shumkov** [comment]
Evonet is down in favor of testnet a month ago.

**Comment by imanmousaei** [comment]
so how can we connect to the mainnet?
@shumkov

**Comment by shumkov** [comment]
Dash Platform is not available on mainnet yet, but you can play with testnet already. SDK connects by default to testnet or you can specify `network` option
