### ISSUE TITLE
DashJs can't run in html

### ISSUE THREAD

**Issue by EurekaChen** [dashevo/DashJS#21]
## code 
``` javascript
<script src="https://unpkg.com/dash"></script>
<script>      
  const sdkOpts = {  network: 'testnet' };
  const sdk = new DashJS.SDK(sdkOpts);      
</script>
```
### Current Behavior
get "Uncaught"  error with  message: "An exception occurred"
### Context
Just in simple html
### full html file:
``` html
<!DOCTYPE html>
<html>

<head>
    <script src="https://unpkg.com/dash"></script>
</head>

<body>
    <script>
        const sdkOpts = { network: 'testnet'};
        const sdk = new DashJS.SDK(sdkOpts);
    </script>
</body>

</html>
```

**Comment by Alex-Werner** [comment]
Perfect ! 
Thank you @EurekaChen for the bug report. 
This is similar to https://github.com/seigler/cra-dash-sdk-demo (a React Environment). 
We are already looking into this, it seems to also involve a js-dpp fix (crypto module). 
In any case, am on this, and will keep you updated promptly with the fix :)

**Comment by shumkov** [comment]
Is it still an issue? We fixed gRPC-Web thing so I guess it should work now.

**Comment by thephez** [comment]
Closing for now due to inactivity and probable fix already in place
