### ISSUE TITLE
Using DashJS in a TypeScript file (compilation and IntelliSense errors)

### ISSUE THREAD

**Issue by riongull** [dashevo/DashJS#46]
### Expected Behavior

Since DashJS is written in TypeScript I expected IntelliSense support out of the box.

### Current Behavior

I ran into compilation and IntelliSense issues when consuming the DashJS SDK from a TypeScript file.  I was able to monkey patch it in order to get it working, but I'm not sure my fix is the right way to address the issue (hence an issue rather than a pull request).  

I'm using `dash@3.0.0`, but the problem existed in 2.x and 1.x as well.

The [DashJS typescript documentation](https://dashevo.github.io/DashJS/#/getting-started/with-typescript) shows the following example:

```
import Dash from 'dash';
const clientOpts = {
  network: 'testnet',
  mnemonic: null,
};
const client = new Dash.Client(clientOpts);
client.isReady().then(()=> console.log('isReady'));
```

I got compilation errors, even with the recommended `compilerOptions` in `tsconfig.json`:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true
  }
}
```

### Context

For reference, here are the relevant parts of `~/myproject/node_modules/dash/package.json`:

```
{
  "dependencies": {
    "@dashevo/dapi-client": "~0.12.0",
    "@dashevo/dashcore-lib": "^0.18.0",
    "@dashevo/dpp": "~0.12.1",
    "@dashevo/wallet-lib": "^6.1.0",
    "bs58": "^4.0.1"
  },
  "main": "dist/dash.cjs.min.js",
  "name": "dash",
  },
  "types": "src/SDK/SDK.d.ts",
  "version": "3.0.0"
}
```

### Steps to Reproduce & logs

```
mkdir ~/myproject
npm init
npm install dash
echo $compilerOptionsAbove > tsconfig.json
echo $tsExampleCodeFromDocs > index.ts
tsc -p tsconfig.json
```

For completeness sake, in case anyone reading this issue came here with the following error... 

```
index.ts:1:8 - error TS2613: Module '"/Users/Rion/code/dash/playground/typescript/no
de_modules/dash/src/SDK/SDK"' has no default export. Did you mean to use 'import { D
ash } from "/Users/Rion/code/dash/playground/typescript/node_modules/dash/src/SDK/SD
K"' instead?

1 import Dash from 'dash';
         ~~~~
```
...that's probably because you didn't include `"esModuleInterop": true` in your `tsconfig.json`.  Before figuring that out, you might have just tried the suggestion to `import { Dash } from 'dash'`, but that would have given you this error... 

```
index.ts:6:20 - error TS2708: Cannot use namespace 'Dash' as a value.

6 const client = new Dash.Client(clientOpts);
                     ~~~~
```
...and if you just tried to run the compiled `index.js` file (because `tsc` will compile your code even if it's not happy about it) you would have gotten different runtime errors either way.  You might have then tried `import * as Dash from 'dash'` and compiled that.  That would have given you this TypeScript error...

```
index.ts:6:25 - error TS2339: Property 'Client' does not exist on type 'typeof import("/Users/Rion/code/dash/playground/typescript/node_modules/dash/src/SDK/SDK")'.

6 const client = new Dash.Client(clientOpts);
                          ~~~~~~
```
...but `node index.js` would have worked just fine at runtime.  At this point it's just a TS (not a JS) error.  As far as I know `import * as Dash from 'dash'` is the same as `import Dash from 'dash'` with `"esModuleInterop": true`, so it may be worth documenting the `import * as Dash` option as well, in case someone is working in an environment where they don't have access to the `tsconfig.json` to modify it.

So now it's working but you're still not getting IntelliSense and you have an annoying compile and IDE error.  TS is looking for types where `package.json` told it to (`"types": "src/SDK/SDK.d.ts"`).  **Changing this to `"types": "src/"` and restarting your IDE fixes the problem.**   TS gives you no errors, you now have IntelliSense, and the compiled `index.js` file runs without error.

### Recommendation

I'm not sure if this is the correct fix.  It seems like maybe changing the build process might be better (or changing source code).  I notice there are no `.d.ts` files in the build folder where I've seen them in other projects.  Not sure what the best approach is, but I've done my best to document all the errors so the issue is clear.

Once I got everything working and IntelliSense was doing its job (telling me what methods existed on classes, what arguments were required in functions, etc), I noticed some discrepancies between what TS was telling me a function signature was, what the documentation said it was, and what actually worked (for example, [paying to an address](https://dashevo.github.io/DashJS/#/examples/pay-to-another-address)).  I can go into more detail about that if anyone is interested.

### One other question

What's the reasoning behind uppercasing "Dash" on `import Dash from 'dash'` (or `const Dash = require('dash')`?  Doesn't that typically communicate that the variable is to be used as a constructor (e.g. `const dashInstance = new Dash`)?  In this case it's just a namespace for other constructors (e.g. Client), isn't it?

**Comment by antouhou** [comment]
Fixed by https://github.com/dashevo/DashJS/pull/52; Waiting to merge

**Comment by antouhou** [comment]
Regarding the question at the end - the JS convention is to call namespaces in the upper camel case as well

**Comment by riongull** [comment]
Thanks for that namespace convention insight.  Didn't know that.
Good to close this now with #53
