### ISSUE TITLE
HTTP ruta # 121042882

### ISSUE THREAD

**Issue by C3s1r12z3** [dashevo/DashJS#51]
### Expected Behavior

Please describe the behavior you are expecting

### Current Behavior

What is the current behavior?

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

### Steps to Reproduce & logs

If case of a bug, please list here how to reproduce along with logs or code snippets.

**Comment by C3s1r12z3** [comment]
Dirección de propietario y de cuenta bancaria

**Comment by antouhou** [comment]
What is this exactly about?

**Comment by antouhou** [comment]
This issue doesn't make any sense and no further comments were received from the issue's author. Closing.
