### ISSUE TITLE
Delays and Errors (codes 13 and 14), usually from 159.89.8.31

### ISSUE THREAD

**Issue by riongull** [dashevo/DashJS#54]
### Expected Behavior

Reliable, repeatable responses from calls to dash platform.

### Current Behavior

I have some very basic code testing `dash 3.0.2`.  Typically it takes 3 to 4 seconds for `dash.isReady()` and then 0.3 - 0.4 seconds for `dash.platform.identities.get(aValidId)` to resolve.  

Every now and then (sometimes back to back, sometimes after 10 successful calls) it takes 20 to 30 seconds to resolve either or both of the above, after which it usually (but not always) results in an error.  The errors are usually `code: 13` or `code: 14`, and might (always?) be (solely?) related to `159.89.8.31`.

##### Sample Errors

`ETIMEDOUT` Error:
```
error: Failed to perform standard injectionsconnect ETIMEDOUT 159.89.8.31:3000 { Error: connect ETIMEDOUT 159.89.8.31:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '159.89.8.31',
  port: 3000,
  config:
   { url: 'http://159.89.8.31:3000',
     method: 'post',
     data:
      '{"jsonrpc":"2.0","method":"getBestBlockHash","params":{},"id":1}',
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json;charset=utf-8',
        'User-Agent': 'axios/0.19.2',
        'Content-Length': 64 },
     transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     timeout: 20000,
     adapter: [Function: httpAdapter],
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus] },
```

Error 13:
```
{ Error: 13 INTERNAL: Internal error
    at Object.exports.createStatusError (/sandbox/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/sandbox/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/sandbox/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/sandbox/node_modules/grpc/src/client_interceptors.js:618:8)
    at InterceptingListener._callNext (/sandbox/node_modules/grpc/src/client_interceptors.js:574:12)
    at InterceptingListener.onReceiveStatus (/sandbox/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/sandbox/node_modules/grpc/src/client_interceptors.js:847:24)
  code: 13,
  metadata:
   Metadata {
     _internal_repr:
      { server: [Array], date: [Array], 'content-length': [Array] },
     flags: 0 },
  details: 'Internal error' }
```

Error 14:
```
{ Error: 14 UNAVAILABLE: failed to connect to all addresses
    at Object.exports.createStatusError (/sandbox/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/sandbox/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/sandbox/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/sandbox/node_modules/grpc/src/client_interceptors.js:618:8)
    at InterceptingListener._callNext (/sandbox/node_modules/grpc/src/client_interceptors.js:574:12)
    at InterceptingListener.onReceiveStatus (/sandbox/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/sandbox/node_modules/grpc/src/client_interceptors.js:847:24)
  code: 14,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'failed to connect to all addresses' }
```

   
### Context

This happens on my local setup as well as the codesandbox I set up (see below).

### Steps to Reproduce & logs

1. Visit https://codesandbox.io/s/dash-test-y0b7n?file=/src/index.ts
2. Drag the "Terminal" pane up to the top for better viewing (don't need the browser pane).
3. Make a trivial edit (like adding a space after `"Done"` in the `main().then()` callback.
4. Do `cmd + s` to save file and trigger the sandbox to re-run.
5. Repeat step 3 and 4 until you see errors.

I think this might be a known issue related to a rouge masternode but I didn't see an issue here, and maybe there's more to it than the bad masternode, so I figured I'd post it.

**Comment by riongull** [comment]
Just tried to reproduce again and ran into the odd case where the call worked but took 23 seconds:

```
[INFO] 01:17:09 Restarting: /sandbox/src/index.ts has been modified
Using ts-node version 8.10.1, typescript version 3.8.3
warn: Running on a NodeJS env without any specified adapter. Data will not persist.
Loading
Done loading: 23.611 s.
Getting data
Done getting data: 0.362 s.
9983954
Done
```

**Comment by antouhou** [comment]
Well, this is what happens when we have offline nodes on the network. I've mentioned yesterday on discord that the solution would be is to have a ban-and-retry policy in the client. This is in our backlog for the current/next week

**Comment by cloudwheels** [comment]
I've been doing some pretty heavy development on the Platform and I would say that these errors occur on well over 50% of the calls I make to the network, in essence rendering it unusable in any practical sense. There is no way I would currently introduce anyone not already familiar with all the hard work and effort going into this project to working with it at this stage: they would simply find it to be broken. For my 2 cents, addressing this should be an absolute top priority, and if there's any useful contribution that can be made I would be very willing to do so.

**Comment by antouhou** [comment]
@riongull @cloudwheels I've enable DKG and PoSe bans on evonet, and all rogue nodes are gone now

**Comment by riongull** [comment]
Nice work @antouhou.  As far as I’m concerned we can close this. I haven’t seen any errors since the fix.

**Comment by Alex-Werner** [comment]
Thank you @riongull for this issue. 
I'm closing this issue, do not hesitate to reopen it if you find it not fixed.
