### ISSUE TITLE
feature: Allow client to select own node(s)

### ISSUE THREAD

**Issue by cloudwheels** [dashevo/DashJS#56]
### Context
The problems caused by a single rogue node as described in #54 and #55 have been causing a significant headache for developers using the platform in recent days.

Whilst, of course, it is necessary to implement a fix based on banning & retry, an effective workaround, initially [suggested by community member @dashameter](https://discordapp.com/channels/670271785974890526/670540408593448980/709251715232301096), is to NAT dapi requests to a selected node.

Although this seems contrary to the objectives of a *distributed* API, as @dashameter points out:
> the decentralized nature is for when you don't know which node to trust, and the nodes between each other and L1, if you know which node to trust, it's like running your own full node in bitcoin

Therefore, a proposed feature for DashJS / Dapi is that the client should be able to have control over using a single or group of specified nodes, overriding the MN determination process.

**Comment by antouhou** [comment]
Should be fine now: https://github.com/dashevo/DashJS/issues/54#issuecomment-627353686
Can I close the issue?

**Comment by cloudwheels** [comment]
Closing...
