### ISSUE TITLE
Transaction event listener not working

### ISSUE THREAD

**Issue by readme55** [dashevo/DashJS#93]
I can successfully register the tx listener - but it wont execute when a new tx comes in.

## Steps to Reproduce (for bugs)

I already talked to Alex-Werner and modified my code according to his hints. But it still does not work:
https://discordapp.com/channels/670271785974890526/670540408593448980/722765071792603257
```
client = new Dash.Client(sdkOpts);
account = await client.getWalletAccount();
account.on('FETCHED/CONFIRMED_TRANSACTION', (data) => {
    console.log('FETCHED/CONFIRMED_TRANSACTION');
    console.dir(data)
});
```

## Your Environment

* Version used: DashJS 3.13.3

**Comment by thephez** [comment]
@readme55 I tried a few variations of your code example and was not successful either.

**Comment by Alex-Werner** [comment]
Thank you @readme55 for this issue. 
This got a fix here : https://github.com/dashevo/wallet-lib/pull/159 
Sorry for the issue caused :x It will soon land in a new release.
